### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by busterwood** [nunit/nunit-v2-framework-driver#12]
How do I use this?  I've tried dropping the DLLs into my path but it made no difference.  Do I need to configure something?

**Comment by ChrisMaddock** [comment]
You need a `.addins` file in the same directory as the engine, similar to the one at the link below. The path in the .addins file should contain a filepath pointing to the location of nunit.v2.driver.dll.

https://github.com/nunit/nunit-v2-framework-driver/blob/master/nunit.v2.driver.addins

Are you using the NUnit Console? How are you installing it - the addin should install automatically, if you're using either NuGet or the msi installer.
