### ISSUE TITLE
Are v2 addins supported?

### ISSUE THREAD

**Issue by flcdrg** [nunit/nunit-v2-framework-driver#13]
Does the driver provide backwards compatibility for NUnit 2 addins?

I have a test assembly that has an ISuiteBuilder implementation. It would be great to be able to run this assembly using the NUnit 3 test runner, but it doesn't appear to support this at the moment.

**Comment by CharliePoole** [comment]
@flcdrg I know this is pretty old, but if you have sample code it would help us decide what to do.

@ChrisMaddock Re: pre-release review
This doesn't actually make sense to me. We run the tests using V2 code, so V2 addins should work. I would lean toward rejecting it if it can't be confirmed.

**Comment by flcdrg** [comment]
We have finished moving completely to v3 so this is not important to me anymore. I'll close it, but feel free to reopen it if someone else is interested
