### ISSUE TITLE
Remove nunit.v2.driver.addins?

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-v2-framework-driver#14]
I don't understand why the NuGet package for this extension includes it's own `.addins` file. None of our other extensions do.

It wouldn't be picked up by any of the default location methods, as far as I can tell, and I'm not aware of anything which makes this extensions need different location logic to any of our others.

Was it a legacy way of installing? Should i be removed?

**Comment by CharliePoole** [comment]
No it belongs there because the extension directory includes other support assemblies, which are not extensions. It avoids spending extra time scanning those assemblies and, in rare cases, throwing an exception.

**Comment by CharliePoole** [comment]
The file is found when another .addins file refers to the directory. This is exactly the case when the runner itself is installed as a nuget package.

When repackaging, you need to figure out your own set of references to allow all extensions to be found. You could include such addins in one strategy or exclude them in a different strategy. You could also use them when deciding what to include in your own addins file.

By the way, no addins file implies all dll are extensions.

**Comment by ChrisMaddock** [comment]
Ah ok - I didn't realise .addins files could be chained. Cool, thanks!
