### ISSUE TITLE
Is it possible to use this driver along with NUnit.ConsoleRunner?

### ISSUE THREAD

**Issue by jpierson** [nunit/nunit-v2-framework-driver#20]
I was considering making use of the [NUnit.ConsoleRunner](https://www.nuget.org/packages/NUnit.ConsoleRunner/) nuget in order to make each project's console runner configurable per project in our custom build system but if I go this route it doesn't look like there is any obvious way to integrate this V2 driver to run on projects that contain NUnit 2.x tests. Am I right? Is there a corresponding console runner package for NUnit 2 that I should be using for these projects instead?

**Comment by rprouse** [comment]
This project does allow for the running of NUnit 2 tests from the NUnit 3 console. If you install NUnit.ConsoleRunner and NUnit.Extension.NUnitV2Driver, it will add the ability to run your NUnit 2 tests. Alternatively, you can install just NUnit.Console which pulls in the v2 driver and other common extensions.

For more information, I wrote a blog post explaining the difference between the various packages, http://www.alteridem.net/2016/11/08/nunit-console-nuget-packages/
