### ISSUE TITLE
Use NUnit V2 Core package rather than hard coded 2.6.4 binaries

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-v2-framework-driver#22]
With the NUnit 2.6.6 release, I plan to put out a package with the nunit.core and nunit.core.interfaces assemblies. It's aimed specifically at the v2 framework driver as well as any other code that wants to use V2 at this low level.

I propose that once the package is created we use it here updating to 2.6.6. This opens the possibility of fixing an occasional bug that affects the v2 driver in the V2 core itself.

**Comment by cyanite** [comment]
Very good idea. I've just done a personal build of nunit-console with a custom version of the v2 driver with updated nunit v2 libraries from that project, including my open pull request there, which we use to run our mixed v2-v3 suites at my workplace. It works great.

**Comment by CharliePoole** [comment]
@cyanite There is some ongoing discussion with the NUnit Project team about where the V2 framework driver will be maintained and by whom. Hopefully that will be resolved soon and we can move ahead with this (or some other) plan. 😄

**Comment by CharliePoole** [comment]
@nunit/engine-team I see two of you have given a thumbs up, but no comments from anyone. Our offline discussions about moving this project elsewhere seem to be at an impasse. Do you see any problems with this approach? Do you want a PR? Kindly use your words. 😃

**Comment by ChrisMaddock** [comment]
PR sounds good to me. 👍🏻

**Comment by jnm2** [comment]
Agreed!

**Comment by CharliePoole** [comment]
Started work but can't get permission from nuget.org to upload the NUnit.Core package, even though there is none by that name and I'm a holder of the prefix. Waiting to hear back from support.

**Comment by CharliePoole** [comment]
@nunit/framework-and-engine-team It turns out that JetBrains has a de-listed package called NUnit.Core, which is the name I used for the package containing the V2 nunit.core and nunit.core.interfaces assemblies.

I think it's up to the @nunit/core-team to decide whether to pressure JetBrains to get rid of this package name. I'm inclined to change my naming to NUnitV2.Core but I'll wait for your feedback.

**Comment by jnm2** [comment]
I'd like us to end up in control of that package either way.

**Comment by CharliePoole** [comment]
Do you know what it does? There's no actual info at https://nuget.org/packages/NUnit.Core and it hasn't been updated for three years.

**Comment by jnm2** [comment]
It's pretty barebones. This is a cool site that lets you browse the contents of every NuGet package:

https://www.fuget.org/packages/NUnit.Core

In particular see the assemblies list.

**Comment by CharliePoole** [comment]
That's good to know about. I didn't want to bother downloading it to check, as I already only care about the name. Seems like they were trying to do something similar to what I've done, except they included the nunit.utill assembly as well. We stopped using it for the v2 framework driver ourselves since the engine handles all the stuff that was originally in nunit.util. IMO, we're really only concerned with control of the name, not the package itself.

Any thoughts on whether I should call this NUnitV2.Core?

**Comment by jnm2** [comment]
Yes, sorry. The name is what's important to me to control.

We had consensus that we didn't want to use NUnitv2 for the framework package itself, so ideally we'd be consistent. I would hate to make you wait though. @nunit/core-team, can you weigh in on this? Which of you would be interested in talking to JetBrains? I'm willing but probably carry the least weight :D

**Comment by ChrisMaddock** [comment]
I'm slightly apathetic to be honest.

We now own the 'nunit' prefix of NuGet, so all future such packages can't be created. This is a legacy NUnit 2 package, which is delisted - so, in my opinion, isn't a problem, other than the fact that Charlie wants to create this new package of the same name now.

I'd be happy with us going for either option - personally, I'd just rename as NUnitV2.Core, as that's the easier path, but if someone else wants to try talking to JetBrains - that's fine by me. 🙂

**Comment by CharliePoole** [comment]
I actually prefer NUnitV2.Core since it makes clearer what it does. I was using NUnit only because you guys preferred it.

**Comment by CharliePoole** [comment]
@jnm2 As far as I have seen, nobody carries much weight with them.

**Comment by jnm2** [comment]
That makes sense. For the framework package, I like the fact that the ID is the same since that means you can't reference both v2 and v3 framework in the same project. But for the NUnit core assemblies you're distributing, side by side makes more sense?

**Comment by CharliePoole** [comment]
@jnm2 It's a package for use by those writing V2 runners, not for general users. If somebody wanted to create a runner that handled both V2 and V3, then side-by-side would make sense but of course there is no `NUnit.Core` package anyway. We generally use "Core" to mean .NET Core in NUnit 3. That's the main reason I prefer `NUnitV2.Core`. 

It is too bad that "Core" has so many overloaded meanings!

**Comment by CharliePoole** [comment]
I'm going with NUnitV2.Core and will release it in 2.7, which you can see here: https://github.com/nunit-legacy/nunitv2/milestone/2.7

In this case, I'm using the minor version update to indicate that several components are being dropped, while still keeping it less than 3.0.
