### ISSUE TITLE
V2 Driver does not support id filters

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-v2-framework-driver#29]
This doesn't impact the console runner or VS adapter, which don't use id filters. In a GUI, they are the most natural thing to use. 

If the GUI knew when it was running V2 tests, it could pass a different filter. However, it doesn't know that and we wouldn't want each runner to have to deal with this separately.

The problem is exacerbated by the fact that the exception generated is swallowed whole by `MasterTestRunner`, which uses a `when` clause to only handle certain exceptions. Other exceptions are allowed to continue. That would be OK except that the method where this happens is run on a worker thread so the exception goes unhandled.

I'll fix this by first handling the exception and reporting it. Beyond that, we need to decide if the engine should do a filter conversion or the V2 driver should do it. Currently, the V2 driver converts other filters, but not the id filter.

It would also be possible to upgrade the legacy V2 code to directly handle id filters, in which case that feature could be used by a new release of the V2 driver.

I'm assigning this to myself for the purpose of at least reporting the exception. Some discussion on how to take it further is needed to take the next steps.

**Comment by CharliePoole** [comment]
@mikkelbu @ChrisMaddock @rprouse 

OK, not as easily doable in the driver alone as I hadhoped. I'll run through the options I've tried.

1. It __would__ be doable in the driver in one way: The driver would save an index to the loaded tree of tests, with the ID as key. Whenever an id filter was used, it would look up the test and then create an entirely different type of filter that selects that test alone. The V2 NameFilter would do the job. Once I saw that a complete search of the tree would be needed before even beginning to apply the filters, I rejected this approach.

2. I came up with a hybrid approach. The driver would create a NameFilter, with only runner id and test id. The fullname of the test would be omitted. NUnit core would be modified so that a null fullname matched everything. I tried this out and found it made a visible breaking change in nunit v2, so I think it's out as well.

3. Finally, I have this option... create an id filter for the V2 framework. It isn't breaking because it has never existed before. Only the V2 driver would use it, translating from NUnit 3 IdFilter to the new NUnit V2 IdFilter.

This is the best I can come up with, although it seems crazy to be adding a new "feature" to V2! What do you guys think?

**Comment by rprouse** [comment]
The third approach seems reasonable. It is really just down to if you want to do the work or not and how much you need it for the GUI. NUnit 3.7 has 65K downloads since last October which shows there is still some use, but the tide has definitely turned with 3.11 getting over 4.5 million downloads in a similar timeframe and the latest release getting five times the downloads in a month. You've been maintaining the v2 framework, so please do what you feel is best.

**Comment by CharliePoole** [comment]
Thanks. Amount of work is the least for 2, which breaks V2. Option 3 is next.

BTW, I asked because you all are the biggest consumer of NUnit V2. Each copy of the V2 framework driver gets the updated V2 core, including those bundled with NUnit.Console. In a similar period, there were about 1 million downloads of  the extension alone and 4.2 million downloads of NUnit Console. Of course, we don't know how many of the latter are in actual use running V2 tests, but all those folks are getting the V2 legacy code.

Key problem is to add this without any negative impact on you, on those users and on the direct users of V2. Ideally, the tests will tell us that.
