### ISSUE TITLE
Name and Fullname are the same in V3 XML format

### ISSUE THREAD

**Issue by Stefan-Ilic** [nunit/nunit-v2-framework-driver#39]
Hi,

I noticed that when running V3 tests with the V3 console against an assembly, the output XML's first test-suite element (with type="Assembly") has a `name` attribute, which is only the assembly name (like `Foo.dll`) and a `fullname` (like `C:\Bar\Foo.dll`).

Running V2 tests with the V3 runner and the nunit-v2-framework-driver seems to have `C:\Bar\Foo.dll` in both the `name` and `fullname` attribute.

I'd expect `name` to be the assembly file name with V2 tests as well.

Best regards,
Stefan Ilic

**Comment by CharliePoole** [comment]
What versions of the v2 framework driver, v2 framework and console or other runner are you using?

**Comment by Stefan-Ilic** [comment]
NUnit Framework Version: 2.6.3
NUnit.ConsoleRunner Version: 3.11.1
NUnit.Extension.NUnitV2Driver Version: 3.8.0

**Comment by CharliePoole** [comment]
I'm confirming this for both nunit 3 and nunit v2 tests run with output format `nunit2`. At the moment, it's unclear whether fixing the driver extension will fix both problems or if the nunitv2 output writer extension will require changes as well.
