### ISSUE TITLE
NUnit 3 console should produce xml events for ITestEventListener which contain unique id in the scope of all test agents for NUnit 2 tests

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/nunit-v2-framework-driver#5]
See new issue https://github.com/nunit/teamcity-event-listener/issues/28
See issue https://github.com/nunit/nunit-console/issues/37
See PR https://github.com/nunit/nunit-console/pull/38

**Comment by NikolayPianikov** [comment]
@CharliePoole where I can get last nuget packages for integration tests?

**Comment by rprouse** [comment]
Our MyGet feed should contain master builds for each project. If any project is missing, please let us know. The feed addresses are;

v2 - https://www.myget.org/F/nunit/api/v2
v3 - https://www.myget.org/F/nunit/api/v3/index.json

**Comment by CharliePoole** [comment]
@NikolayPianikov But note that "latest" means dev builds, not the latest production releases, which are not on the myget feed at all.

**Comment by CharliePoole** [comment]
@rprouse Do we want to mirror our nuget packages on myget and just use myget for our dev work?

**Comment by rprouse** [comment]
My mistake, I thought we were now posting master builds to MyGet automatically.

@CharliePoole I don't see MyGet as a place to mirror our packages, but I thought it could be a step up from AppVeyor CI builds, possibly builds of master after every merge so that the various projects always have access to the latest for integration testing and development without having to configure a feed for each project. The project feed on AppVeyor is password protected and I can't turn that off, so we can't seem to do a master feed there.

**Comment by CharliePoole** [comment]
@rprouse I'm not sure we are talking about the same thing. Every time we merge into master, appveyor builds the result of that merge. It is uploaded to myget using a -dev suffix. Production releases, which are built manually at this time, are not uploaded to myget but to nuget.org - you just did one for nunit.framework and I did one for nunit-console.

If by "latest" @NikolayPianikov means the latest production release, he should go to nuget. If he wants the latest merged master build, he should use myget. I believe he is actually testing against both.

If we wanted to, we could mirror the actual non-pre-release production releases on nuget on our myget feed. That way developers could get either a production release or a dev release from the same place by checking/unchecking the pre-release box.

**Comment by rprouse** [comment]
@CharliePoole it sounds like we are talking about the same things then. What you are describing is how I thought it worked. When @NikolayPianikov asked for the `last nuget packages for integration tests` I assumed that he knows where the released versions are so therefore thought he wants the latest builds of master to test.

At any rate, I think @NikolayPianikov has the info he needs.

**Comment by rprouse** [comment]
This was completed with #6
