### ISSUE TITLE
Explicitness of tests is ignored in the presence of a negated filter

### ISSUE THREAD

**Issue by philipcarlsen** [nunit/nunit-v2-framework-driver#7]
It seems, in a project referencing nunit.framework v2.6, that nunit3-console when given "--where=cat != SomeCategory" at the command line also runs tests marked Explicit. In the absence of any filter, tests marked Explicit are not run.

I'm filing the issue in the nunit-v2-framework-driver project rather than the nunit-console project as it seems the most likely place for the error. I would assume that others before me would have discovered this issue, as it runs contrary to the way category filters should work wrt. explicitness being selected in a NotFilter.

**Comment by CharliePoole** [comment]
This could be a bug in
1. The V2 driver
2. The embedded V2 code that runs the tests.
3. The 2.6 framework

Since only item 1 is currently maintained, let's hope that's it.:-)

An easy test would be to try it under the 2.6.4 console using the --exclude option.

**Comment by philipcarlsen** [comment]
I can verify that the 2.6.4 runner correctly abstains from running Explicit tests.

I wasn't aware that item 1. and item 2. was separate things. I thought only the V2 driver was involved in detecting and running tests.

I think I have enough to go on for looking into the V2 driver (though I have yet to setup a local development environment for NUnit), but I'm not so sure about the embedded test run code. Could you point out for me where to start looking? Or is it in your opinion likely that it will be apparent to me when I actually start debugging?

**Comment by CharliePoole** [comment]
@philipcarlsen That's very useful info.

The V2 driver contains code that references and uses assemblies from the NUnit 2.6.4 distribution, which are bundled with the extension. You won't find any source code for these assemblies in the extension.

Since these are the same assemblies distributed with NUnit 2.6.4, that lets us know that they are capable of handling Explicit tests correctly. It's a question of how the adapter is using them.

When a test is run, the XML representation of the filter to be used is passed to the driver The method CreateNUnit2TestFilter is used to translate it to a V2 NUnit.Core.TestFilter. We would want to check what filter is being created and passed to the core to use in running the tests.

**Comment by philipcarlsen** [comment]
Okay. I think I've narrowed the problem down to the way that the v2-framework-driver constructs thet TestFilter (of nunit.core.interfaces) from XML, which uses "TestFilter.FromXML".

TestFilter.FromXML does not account for the toplevel-ness of not-filters, which just results in a NotFilter with toplevel=false, and the resulting NotFilter thus no longer denies explicit tests.

**Comment by CharliePoole** [comment]
I'm on my phone and not looking at the code but that makes sense. Did you plan to do a PR for this?

**Comment by philipcarlsen** [comment]
Yes :-)

**Comment by CharliePoole** [comment]
I invited you as a contributor so you can be assigned the issue.

**Comment by philipcarlsen** [comment]
That's great :-) However, I'm not sure if I need to do something to acknowledge the invite. I can't seem to find any indication of this in the github ui.

**Comment by ChrisMaddock** [comment]
I'm not sure of the rest of the process, but it looks like I can assign you the issue! 😄

**Comment by rprouse** [comment]
@philipcarlsen try going to https://github.com/nunit and see if you are prompted to accept the invitation to the contributors team. I checked and you are still pending.

**Comment by CharliePoole** [comment]
@ChrisMaddock Maybe being invited is sufficient for that purpose!

**Comment by philipcarlsen** [comment]
Visiting the nunit-organisation github page did the trick :-)

**Comment by CharliePoole** [comment]
Fixed in PR #8
